//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProcess
    {
        public int ProcessId { get; set; }
        public string ProcessDescription { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string ProcessType { get; set; }
        public Nullable<decimal> ProcessAmount { get; set; }
        public Nullable<int> BankId { get; set; }
    
        public virtual TblBank TblBank { get; set; }
    }
}
