//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStock
    {
        public int StockId { get; set; }
        public string StockTitle { get; set; }
        public Nullable<int> StockNumbers { get; set; }
        public Nullable<decimal> StockPrice { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
    }
}
